import{S as m,a as f,i as L}from"./assets/vendor-c145bea9.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerpolicy&&(o.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?o.credentials="include":e.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const s={form:document.querySelector(".search-form"),input:document.querySelector(".search-inp"),searchBtn:document.querySelector(".search-btn"),gallery:document.querySelector(".gallery"),loadMoreBtn:document.querySelector(".load-btn"),loader:document.querySelector(".loader")},d=new m(".gallery-item a",{captionsData:"alt",captionDelay:250});f.defaults.baseURL="https://pixabay.com/api";const b="41899926-74a7536d4d492e936dbb67b5b",a={page:1,query:"",maxPage:0,per_page:40};s.form.addEventListener("submit",q);async function q(r){if(r.preventDefault(),hideLoadMoreBtn(),s.gallery.innerHTML="",a.page=1,a.query=s.form.query.value.trim(),!a.query){c("The search field can't be empty😉! Please, enter your request!");return}try{u();const{hits:t,totalHits:n}=await y(a);a.maxPage=Math.ceil(n/a.per_page),p(t,s.gallery),d.refresh(),t.length>0?(showLoadMoreBtn(),s.loadMoreBtn.addEventListener("click",M)):(hideLoadMoreBtn(),c("Sorry, there are no images matching your search query🙃. Please, try again!")),hideLoader()}catch(t){console.log(t)}finally{s.form.reset(),a.page===a.maxPage&&(hideLoadMoreBtn(),c("We're sorry, but you've reached the end of search results🙃!"))}}async function M(){a.page+=1;try{u(),hideLoadMoreBtn();const{hits:r}=await y(a);p(r,s.gallery),d.refresh(),hideLoader(),S(),showLoadMoreBtn()}catch(r){console.log(r)}finally{a.page===a.maxPage&&(hideLoadMoreBtn(),c("We're sorry, but you've reached the end of search results🙃!"))}}async function y(r,t=1){return u(!0),f.get("/",{params:{key:b,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:40,page:t}}).then(({data:n})=>n)}function p(r){const t=r.map(({webformatURL:n,largeImageURL:i,tags:e,likes:o,views:l,comments:g,downloads:h})=>`
        <li class="gallery-item">
  <a class="gallery-link" href="${i}">
    <img
      class="gallery-image"
      src="${n}"
      alt="${e}"
    />
    <p class="gallery-descr">Likes: <span class="descr-span">${o}</span> Views: <span class="descr-span">${l}</span> Comments: <span class="descr-span">${g}</span> Downloads: <span class="descr-span">${h}</span></p>
  </a>
</li>`).join("");s.gallery.insertAdjacentHTML("beforeend",t),d.refresh()}function c(r){L.show({class:"error-svg",position:"topRight",icon:"error-svg",message:r,maxWidth:"432",messageColor:"#fff",messageSize:"16px",backgroundColor:"#EF4040",close:!1,closeOnClick:!0})}function u(r=!0){s.loader.style.display=r?"inline-block":"none"}function S(){const r=document.querySelector(".gallery-link").getBoundingClientRect();window.scrollBy({top:r.height*2,left:0,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
