import{S as L,a as y,i as q}from"./assets/vendor-c145bea9.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&c(l)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function c(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const s={form:document.querySelector(".search-form"),input:document.querySelector(".search-inp"),searchBtn:document.querySelector(".search-btn"),gallery:document.querySelector(".gallery"),loadMoreBtn:document.querySelector(".load-btn"),loader:document.querySelector(".loader")},d=new L(".gallery-item a",{captionsData:"alt",captionDelay:250});y.defaults.baseURL="https://pixabay.com/api";const M="41899926-74a7536d4d492e936dbb67b5b",a={page:1,query:"",maxPage:0,per_page:40};s.form.addEventListener("submit",S);async function S(r){if(r.preventDefault(),i(),s.gallery.innerHTML="",a.page=1,a.query=s.form.query.value.trim(),!a.query){u("The search field can't be empty😉! Please, enter your request!");return}try{f();const{hits:o,totalHits:n}=await p(a);a.maxPage=Math.ceil(n/a.per_page),g(o,s.gallery),d.refresh(),o.length>0?(m(),s.loadMoreBtn.addEventListener("click",v)):(i(),u("Sorry, there are no images matching your search query🙃. Please, try again!")),hideLoader()}catch(o){console.log(o)}finally{s.form.reset(),a.page===a.maxPage&&(i(),u("We're sorry, but you've reached the end of search results🙃!"))}}async function v(){a.page+=1;try{f(),i();const{hits:r}=await p(a);g(r,s.gallery),d.refresh(),hideLoader(),w(),m()}catch(r){console.log(r)}finally{a.page===a.maxPage&&(i(),u("We're sorry, but you've reached the end of search results🙃!"))}}async function p(r,o=1){return f(!0),y.get("/",{params:{key:M,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:40,page:o}}).then(({data:n})=>n)}function g(r){const o=r.map(({webformatURL:n,largeImageURL:c,tags:e,likes:t,views:l,comments:h,downloads:b})=>`
        <li class="gallery-item">
  <a class="gallery-link" href="${c}">
    <img
      class="gallery-image"
      src="${n}"
      alt="${e}"
    />
    <p class="gallery-descr">Likes: <span class="descr-span">${t}</span> Views: <span class="descr-span">${l}</span> Comments: <span class="descr-span">${h}</span> Downloads: <span class="descr-span">${b}</span></p>
  </a>
</li>`).join("");s.gallery.insertAdjacentHTML("beforeend",o),d.refresh()}function u(r){q.show({class:"error-svg",position:"topRight",icon:"error-svg",message:r,maxWidth:"432",messageColor:"#fff",messageSize:"16px",backgroundColor:"#EF4040",close:!1,closeOnClick:!0})}function f(r=!0){s.loader.style.display=r?"inline-block":"none"}function w(){const r=document.querySelector(".gallery-link").getBoundingClientRect();window.scrollBy({top:r.height*2,left:0,behavior:"smooth"})}function m(){s.loadMoreBtn.classList.remove("is-hidden")}function i(){s.loadMoreBtn.classList.add("is-hidden")}
//# sourceMappingURL=commonHelpers.js.map
